### ISSUE TITLE
What's the right home for this project?

### ISSUE THREAD

**Issue by jimklo** [jelmer/subvertpy#29]
I've found three different locations for this project:

- https://jelmer.uk/code/subvertpy/
- https://www.samba.org/~jelmer/subvertpy/
- https://github.com/jelmer/subvertpy/

Which is the one I should be looking at?

[PyPi](https://pypi.org/project/subvertpy/) points to [here](https://jelmer.uk/code/subvertpy/) however the downloads are currently broken.

**Comment by jelmer** [comment]
On Thu, Nov 08, 2018 at 01:59:54PM -0800, Jim Klo wrote:
> I've found three different locations for this project:
> 
> - https://jelmer.uk/code/subvertpy/
> - https://www.samba.org/~jelmer/subvertpy/
> - https://github.com/jelmer/subvertpy/
> 
> Which is the one I should be looking at?
> 
> [PyPi](https://pypi.org/project/subvertpy/) points to [here](https://jelmer.uk/code/subvertpy/) however the downloads are currently broken.

The correct homepage is https://jelmer.uk/code/subvertpy 
https://github.com/jelmer/subvertpy/ contains the GitHub mirror and is
used for issue tracking. Downloads appear to work for me on both
github and jelmer.uk. What URL did not work for you?

http://samba.org/~jelmer/subvertpy is outdated; I've changed it to
redirect to the new homepage instead.

Jelmer

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by jimklo** [comment]
The downloads on PyPi are/were broken.  I’m currently on mobile and can’t test. 

https://pypi.org/project/subvertpy/

My guess is that it’s an outdated link in your setup.py?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jelmer** [comment]
Ah! Thanks, I'll get that fixed.

**Comment by jayvdb** [comment]
https://jelmer.uk/code/subvertpy is reporting "Internal Server Error" again.  c.f. https://github.com/jelmer/silver-platter/issues/5

**Comment by jelmer** [comment]
This is fixed.
